# inventory/hosts.yml
all:
  children:
    windows:
      hosts:
        Web2019:
          ansible_host: 172.25.21.140
        Ftp2022:
          ansible_host: 172.25.21.162
      children:
        iis_web:
          hosts:
            Web2019:
        iis_ftp:
          hosts:
            Ftp2022: